#!/usr/bin/env bash
# script to configure nginx to redirect on request to permanently moved page
SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://polymath.me permanent;
        }
}"
echo -e $SERVER_CONFIG | sudo tee /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
        sudo service nginx start
else
        sudo service nginx restart
fi
